### ISSUE TITLE
Dataset download API

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/website#17]
Heya website peeps!

Please can we have the ability to pull down the data we have about the hackspaces we have info about?

I'm not entirely sure how this information might be used, but I don't see a reason not to make it available should people want to do funky Open Data style stuff on it :)

Ta!

Ian

**Comment by Axford** [comment]
As of commit: https://github.com/UKHackspaceFoundation/website/commit/6d0f9e4771c085e249c635745d4affd00421d0d1

there are now two dataset endpoints available:

/spaces - basic space data in a simple json format
/geojson  - geojson file including basic space info as feature properties

**Comment by idnorton** [comment]
Thanks @Axford I'll close the issue off.
