### ISSUE TITLE
New accounts are linked to a commit?

### ISSUE THREAD

**Issue by syberphunk** [UKHackspaceFoundation/website#20]
Links to https://github.com/UKHackspaceFoundation/website/commit/9b25f48

![gitinfo](https://cloud.githubusercontent.com/assets/234857/25071110/3e405970-22a7-11e7-8f69-628401ea7ee7.PNG)

**Comment by Axford** [comment]
No - that page just allows you to view the latest commit that has been applied to the live site.  will secure this so only staff can see it
