### ISSUE TITLE
Allow individual members to join

### ISSUE THREAD

**Issue by russss** [UKHackspaceFoundation/website#5]
People should be able to join the organisation as individual members, including:

* General signup (I think this still needs to include postal address, etc) with agreement to code of conduct
* Details of why we should let the person in as a member
* GoCardless direct debit mandate setup

We then need a way for admins to approve new memberships. 

Once a membership is approved, we need a method of scheduling direct debit payments (which can be used by organisation memberships too). We need to give 3 days' notice of a payment being taken.

I think we decided that an individual membership would be £20/year, but we should make this configurable.

**Comment by Axford** [comment]
Notes on gocardless implementation: https://github.com/UKHackspaceFoundation/website/wiki/GoCardless-implementation

**Comment by russss** [comment]
OK so this is at least initially done, although I expect there will be some residual issues.
