### ISSUE TITLE
Update to 1.11 has broken html rendering for emails

### ISSUE THREAD

**Issue by Axford** [UKHackspaceFoundation/website#80]
e.g. visit /edit-profile and make changes raises a:
 TypeError at /edit-profile
context must be a dict rather than Context.

Underlying code exists in various places, for an example see lines 75-99 in main/forms.py

**Comment by Axford** [comment]
See 1.11 change notes:
https://docs.djangoproject.com/en/dev/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context

**Comment by russss** [comment]
Looks like this one got fixed but the issue wasn't closed.
